const DIFFICULTY_TARGET = 240;
const MINING_DURATION = 5000;
const MINING_REWARD = 50;
const HTTP_PORT = process.env.HTTP_PORT || 3001;

module.exports = {
  DIFFICULTY_TARGET,
  MINING_DURATION,
  MINING_REWARD,
  HTTP_PORT,
};
